language: node_js

node_js:
  - '0.12'

notifications:
  email:
    on_success: change
    on_failure: always

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate < coverage/lcov.info

addons:
  code_climate:
    repo_token: da19db0ba25a3075eb60768d27df019c16879dc47e3be87c5a943ef64d39f039
